create table attendance (id bigint not null, date datetime, state varchar(255), room_id bigint, student_id bigint, primary key (id)) engine=MyISAM;
create table attendance_seq (next_val bigint) engine=MyISAM;
insert into attendance_seq values ( 1 );
create table cost (id bigint not null, month integer, number_of_lesson integer, state varchar(255), teacher_id bigint, primary key (id)) engine=MyISAM;
create table cost_seq (next_val bigint) engine=MyISAM;
insert into cost_seq values ( 1 );
create table refreshtoken (id bigint not null, expiry_date datetime not null, token varchar(255) not null, teacher_id bigint, primary key (id)) engine=MyISAM;
create table refreshtoken_seq (next_val bigint) engine=MyISAM;
insert into refreshtoken_seq values ( 1 );
create table room (id bigint not null, end_date datetime, name varchar(255), number_of_student integer, price_per_lesson decimal(38,2), start_date datetime, state varchar(255), teacher_id bigint, primary key (id)) engine=MyISAM;
create table room_seq (next_val bigint) engine=MyISAM;
insert into room_seq values ( 1 );
create table student (id bigint not null, birthday datetime, full_name varchar(255), state varchar(255), primary key (id)) engine=MyISAM;
create table student_room (room_id bigint not null, student_id bigint not null) engine=MyISAM;
create table student_seq (next_val bigint) engine=MyISAM;
insert into student_seq values ( 1 );
create table teacher (id bigint not null, address varchar(255), birthday datetime, fullname varchar(255), password varchar(255), phone varchar(255), role varchar(255), state varchar(255), username varchar(255), primary key (id)) engine=MyISAM;
create table teacher_seq (next_val bigint) engine=MyISAM;
insert into teacher_seq values ( 1 );
alter table refreshtoken add constraint UK_or156wbneyk8noo4jstv55ii3 unique (token);
alter table attendance add constraint FKa365bouyj2gcosi083mw5qnnh foreign key (room_id) references room (id);
alter table attendance add constraint FKnq6vm31it076obtjf2qp5coim foreign key (student_id) references student (id);
alter table cost add constraint FKjxtcpbgbjh6jf8ilpkpjpsrjw foreign key (teacher_id) references teacher (id);
alter table refreshtoken add constraint FKdupl1tpjgiq9ffu31taabxtdw foreign key (teacher_id) references teacher (id);
alter table room add constraint FK52f7goj96ka380es3uagivlko foreign key (teacher_id) references teacher (id);
alter table student_room add constraint FK5tw2tovm33y96pk72je04nc3o foreign key (student_id) references student (id);
alter table student_room add constraint FKf5420bxfucsk6d0f51y97m49b foreign key (room_id) references room (id);
